name: autofix.ci
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  uv-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv lock --upgrade
      - uses: autofix-ci/action@v1.3.2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: upgrade uv.lock"
          title: "chore: upgrade uv.lock"
          body: This PR updates the uv.lock file with the latest dependency versions.
          branch: update-uv-lock
          delete-branch: true
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        id: pr
      - name: Enable auto-merge for the PR
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: uv-lock
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'pre-commit-ci[bot]') }}
    steps:
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
