name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: valeriangalliat/action-sshd-cloudflared@v1
