name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: ls -l /
      - run: du -sh /
      - run: ls -l /usr/local/share
      - run: du -sh /usr/local/share
      - run: ls -l /opt
      - run: du -sh /opt
