name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: |
          sudo docker image prune --all --force
          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          sudo apt purge r-base x11-common php* nginx
          sudo apt autoremove --purge
      - run: ls -l /mnt
      - run: ls -l /usr/local/share
      - run: sudo du -sh /usr/local/share
      - run: ls -l /usr/share
      - run: sudo du -sh /usr/share
      - run: ls -l /opt
      - run: sudo du -sh /opt
      - run: sudo du -sh /opt/pipx
      - run: sudo du -sh /opt/pipx_bin
      - run: sudo du -sh /opt/google
      - run: sudo du -sh /var
      - run: sudo du -sh /var/log
